name: Build & Test

env:
  GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: "*"

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup npm registry
      run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > .npmrc && echo "registry https://registry.npmjs.org/" >> .yarnrc
        
    - name: Run Install
      uses: Borales/actions-yarn@v4.2.0
      with:
        # Yarn command
        cmd: install
        
    - name: Build
      uses: Borales/actions-yarn@v4.2.0
      with:
        # Yarn command
        cmd: build
      
    - name: Release
      if: github.ref == 'refs/heads/main'
      uses: Borales/actions-yarn@v4.2.0
      with:
        # Yarn command
        cmd: release

